name: PR checks

on: pull_request

jobs:
  build_bff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./movie-smt-bff
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Install packages
        run: go mod download
      - name: Run tests
        run: go test ./... -v
      - name: Build BFF
        run: go build

  build_ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./movie-smt-ui
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build UI
        run: npm run build
